### TEST GET / WEBSITE
GET http://localhost:3000

### TEST GET /dashboard WEBSITE
GET http://localhost:3000/dashboard

### TEST GET /api API
GET http://localhost:3000/api

### TEST POST /api API
POST http://localhost:3000/api
Content-Type: application/json

{
  "name": "Jane Doe",
  "age": 30,
  "email": "test@test.com",
  "address": "1234 Test St"
}

### TEST PUT /api API
PUT http://localhost:3000/api/name
Content-Type: application/json

{
  "value": "Jason Doe"
}

### TEST DELETE /api/email API
DELETE http://localhost:3000/api/email
